### ISSUE TITLE
ReferenceError: self is not defined (snowpack)

### ISSUE THREAD

**Issue by radiosilence** [developit/unfetch#150]
If I try to include this library in a project built with snowpack, I get this error:

```
ReferenceError: self is not defined
```

It is because this file uses an uninitialised global, which seems like a very bad idea:

https://github.com/developit/unfetch/blob/master/packages/isomorphic-unfetch/browser.js

Could we switch it from `self` to something more standard like `global`?

**Comment by radiosilence** [comment]
I've done a PR here which fixes:

https://github.com/developit/unfetch/pull/151

**Comment by developit** [comment]
I mentioned this in the PR, but `global` is not a standard. `self` is a standard - it is defined in all browser environments (document, all worker types, worklet, etc). 

Can you provide a bit more insight into why you need to run the browser entry for isomorphic-unfetch in Node? The code doesn't run there, regardless of whether it uses `self` or Node's `global` - it's a browser-based networking library that relies on XMLHttpRequest.

**Comment by developit** [comment]
I'm going to close this because it should be fixed in [isomorphic-unfetch 4.0.1](https://github.com/developit/unfetch/releases/tag/isomorphic-4.0.1) due to the addition of package exports.

**Comment by zackarydev** [comment]
With v5 of `unfetch` this is still an issue. This occurs when using the polyfill in a node environment.

**Comment by vortesnail** [comment]
still occurs, 4.0.1 or 5.0.0

**Comment by wanwenyun** [comment]
> 

yes, but do you know how to solve it ?

**Comment by vortesnail** [comment]
> > 
> 
> yes, but do you know how to solve it ?

use node-fetch

**Comment by yaizudamashii** [comment]
You need to use node-fetch, and then provide global access.

https://github.com/node-fetch/node-fetch#providing-global-access
